/*
  NOTE: Each line is a day of the year. array[0] is Jan 1, array[31] is Feb. 1
  If we ever have more challenges than number of days in a year,
  we'll make challenges2018.js, challenges2019.js, etc.
*/

module.exports = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Take a string of words and reverse each word. Bonus points if you don't touch punctuation.\n\nExamples:\nHello World -> olleH dlroW\nThis is a string. -> sihT si a gnirts.",
  "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\nFind the sum of all the multiples of 3 or 5 below 1000",
  "Suppose you have a deck of cards. You can perfectly shuffle that list by cutting it at the halfway point, then interleaving the two halves by alternating back and forth between the cards.\n\nE.g. [1 2 3 4 5 6 7 8 9 10] ---> [6 1 7 2 8 3 9 4 10 5]",
  "Given an unsorted array of integers and the sum, find a pair in the array that adds up to the given sum.\n\nE.g. array = [8,7,2,5,3,1]; sum = 10; ---> pair = [8,2]",
  "Your challenge today is to find longest sequence of zeros in binary representation of an integer.",
  "Build a tower by the following given argument: number of floors (integer and always greater than 0).\nTower block is represented as *\n\nE.g. A tower of three:\n[\n  '  *  ', \n  ' *** ',\n  '*****'\n]",
  "Write a program that generates the Baum-Sweet sequence from 0 to some number n.\n\nE.g. given '20' your program would emit: [1,1,0,1,1,0,0,1,0,1,0,0,1,0,0,1,1,0,0,1,0]",
  "Your mission today is to create a basic stopwatch program.\n\nThis program should have start, stop, and lap options",
  "Hello my friends!\n\nYour task today is to implement a linked list in the language of your choice\nhttps://en.wikipedia.org/wiki/Linked_list",
  "Write a function that takes the name of a major scale and the solfège name of a note, and returns the corresponding note in that scale.\n\nE.g. note('C', 'Re') --> 'D'\nnote('A#', 'Fa') --> 'D#'",
  "Create a function that accepts a string as an argument and validates whether the vowels (a,e,i,o,u) and consonants are in alternate order.\n\nE.g. isAlt('amazon') -> true",
  "Create a program that will allow you to enter events organizable by hour. There must be menu options of some form, and you must be able to easily edit, add, and delete events without directly changing the source code.",
  "Make a function that returns the longest word in a sentence.\n\nE.g. 'This is my sentence' --> sentence",
  "Implement a function which takes an array, containing the names of people who like an item on social media. It must return the display text 'like' system from Facebook and other pages.\n\n['Alex','Jacob','Mark','Max'] -> Alex, Jacob and 2 others like this",
  "Your objective today is to create a program that will guess numbers between 1-100 and respond appropriately based on whether users say that the number is too high or too low.\n\nTry to make a program that can guess your number based on user input",
  "Write a function that returns the values of the 'peaks' (or local maxima) of a numeric array.\n\nE.g [3, 2, 3, 6, 4, 1, 2, 3, 2, 1, 2, 3] --> [6, 3]",
  "Hello fellow programmers! Your objective today is to create a basic calculator program.",
  "Write a program that can print the song '99 Bottles of Beer'.",
  "Write a function that uses the ROT-13 encryption algorithm.\n\nE.g. 'Why did the chicken cross the road?' --> 'Gb trg gb gur bgure fvqr!'",
  "Create a function alphabet_soup($str) that accepts a string and will return the string in alphabetical order.\nE.g. 'hello world' becomes 'ehllo dlorw'.\n\nMake sure your function separates and alphabetizes each word separately.",
  "Find the smallest positive number that is evenly divisible by all of the numbers from 1 to 20",
  "A palindrome is a word that can be interpreted the same way in reverse order.\nCreate a function that can detects the longest palindrome.\n\nE.g 'I like racecars that go fast' --> 7",
  "Find the difference between the sum of the squares and the square of the sum of the first one hundred integers.\n\nE.g (first 10 integers). 1^2 + 2^2 + ... + 10^2 = 385;\n(1 + 2 + ... + 10)^2 = 552 = 3025\n3025 − 385 = 2640.",
  "Write a method that gets an array of integer-numbers and return an array of the averages of each integer-number and his follower, if there is one.\n\nE.g. [ 1, 3, 5, 1, -10] --> [ 2, 4, 3, -4.5]",
  "You are given a string of numbers between 0-9.\nFind the average of these numbers and return it as a whole number written out as a string.\n\nE.g. 'zero nine five two' --> 'four'.",
  "Create the classic pascal's triangle. Your function will be passed the depth of the triangle and you code has to return the corresponding pascal triangle upto that depth.\n\nE.g. pascal(5) --> [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]",
  "Write a function that takes CamelCase string and returns the string in snake_case notation.\n\nE.g. 'MoviesAndBooks' --> 'movies_and_books'",
  "Write an algorithm that takes an array and moves all of the zeros to the end, preserving the order of the other elements.\n\nE.g. [false,1,0,1,2,0,1,3,'a'] --> [false,1,1,2,1,3,'a',0,0]",
  "Your task is to sort a given string.\nEach word in the String will contain a single number.\nThis number is the position the word should have in the result.\n\nE.g. 'is2 Thi1s T4est 3a' --> 'Thi1s is2 3a T4est'",
  "Write a function that takes a string of braces, and determines if the order of the braces is valid.\n\nE.g. '([{}])' --> True\n'[({})](]'--> False",
  "Create a function that takes a positive integer number and returns the next bigger number formed by the same digits.\n\nE.g. 2017 --> 2071\n513 --> 531",
  "Move the first letter of each word to the end of it, then add 'ay' to the end of the word. Leave punctuation marks untouched.\n\nE.g. 'Pig latin is cool' --> 'igPay atinlay siay oolcay'",
  "Given a string, replace every letter with its position in the alphabet; 'a' being 1, 'b' being 2, etc.\n\nE.g. 'The sunset sets at twelve o' clock.' -->\n'20 8 5 19 21 14 19 5 20 19 5 20 19 1 20 20 23 5 12 22 5 15 3 12 15 3 11'",
  "Your mission today is to write a unique identifier (uuid) generator.\n\nOutput E.g. 'bf7348be-e4e9-493a-b66e-25d827230905'",
  "Your challenge today is to write a program that can find the amount of anagrams within a sentence. 'snap' would be an anagram of 'pans'\n\nE.g. Bristly birds steal the least stale tales of Tesla that are written on a slate stela (stone slab). --> ???",
  "Write a program that can translate Morse code in the format of ...---...\nA space and a slash will be placed between words. ..- / --.- ",
  "There is a mathematical pyramid with the following pattern:\n1\n11\n21\n1211\n111221\n312211\nYou must write a program to calculate up to the 40th line of this pyramid.",
  "Write a function that computes the day of the week. It'll take three arguments: day, month, and  year.\n\nE.g. ('27', 'January', '2018') --> 'Saturday'",
  "An 'upside up' number is a number that reads the same when it is rotated 180°. 689 and 1961 are upside up numbers.\n\nCount the number of upside up numbers less than ten thousand. 2 and 5 are considered 'upside up' numbers.",
  "Find the number of the year for the given date.\n\nE.g., january 1st would be 1, and december 31st is 365.\nFor extra credit, allow it to calculate leap years, as well.",
  "Create a rock-paper-scissors program with no user input. The computer should play against itself. Make the program keep score and give the option to weigh the chances, so one AI will one more often.\n",
  "Your task today is to implement the Sieve of Sundaram (https://en.wikipedia.org/wiki/Sieve_of_Sundaram) and calculate the list of primes to 10000.\n",
  "Return a list of elements with every block of k elements reversed, starting from the beginning of the list.\n\nE.g. Given the list 12, 24, 32, 44, 55, 66 and the block size 2, the result is 24, 12, 44, 32, 66, 55.",
  "Write a function that takes two strings and removes from the first string any character that appears in the second string.\n\n E.g. ('Daily Programmer', 'aeiou ') --> 'DlyPrgrmmr'.\n\nnote: the space in 'Daily Programmer' is removed",
  "Create a program that will take user input and tell them their age in months, days, hours, and minutes.\n\nE.g. 18 --> 216 months, 6480 days, 155520 hours, and 388800 minutes",
  "Write a program that will convert a phone number that contains letters into a phone number with only numbers and the appropriate dash.\n\nE.g. 1-800-COMCAST --> 1-800-266-2278",
  "Create a program that will remind you to stop procrastinating every two hours with a pop up message!\n\nWho knows, you might use it yourself :)",
  "Hello World! Today, write function that finds the next higher number using the same set of digits.\n\nE.g. 9376544321 --> 9412334567",
  "Chicken McNugget meals are available in quantities of 6, 9, or 20.\nA number is a McNugget number if it can be the sum of the number of McNuggets purchased in an order.\n\nYour task is to determine all numbers that are not McNugget numbers.",
  "Print out the number of times December 25th falls on a Saturday for this century.\n",
  "Write a program that takes a list of integers and a target number and determines if any two integers in the list sum to the target number.n If so, return the two numbers. If not, return an indication that no such integers exist.",
  "In an election, the person with the majority of the votes is the winner. Sometimes, there are no winners.\n\nWrite a program that determines the winner of a vote, or shows that there are no winners due to a lack of majority.",
  "A quine (https://en.wikipedia.org/wiki/Quine_(computing)) is a computer program which takes no input and produces a copy of its own source code as its only output which, in turn, compiles and print out itself. Write one.",
  "Create a web app that should be a list of items with a search box that can filter said items. Highlight what has been searched for.\n\n E.g. if one of the items is 'Apple' and I search 'ap', the first two letters in Apple should be highlighted",
  "Tower of Hanoi is a famous problem. https://en.wikipedia.org/wiki/Tower_of_Hanoi\nThe challenge today is a very famous one where you are to write a function to calculate the total number of moves to solve the tower in fastest way possible",
  "FIZZBUZZ time! Write a program that outputs '1, 2, Fizz, 4, Buzz, Fizz, 7, 8, Fizz, Buzz, 11, Fizz, 13, 14, FizzBuzz, 16, 17, Fizz, 19, Buzz, and so forth until 100.' ",
  "Today's challenge is to determine if a number is a Kaprekar Number. Enjoy :). http://mathworld.wolfram.com/KaprekarNumber.html\n",
  "Print the numbers from 1 to 1000 without using any loop or conditional statements.\nBe creative and try to find the most efficient way!\n",
  "Write a program that prints out the lyrics for '12 days of Christmas'.",
  "Your task today is to implement the Caesar cipher.\n\nFor every letter you want to encrypt, you shift it some number of places down the alphabet to get the letter in the cipher.\nWith a shift of 3, 'A' --> 'D'\n\n'Hello' with a shift of 3 --> 'Khoor'.",
  "Take an array of integers and partition it so that all the even integers in the array precede all the odd integers in the array.\n\nE.g. [7,2,1,4,6,1,8,4,2,5] --> [2,4,6,8,4,2,7,1,1,5]",
  "The Monty Hall Problem (Google it if not familiar)! Write a function that will compare the strategies of switching and not switching doors over many random position iterations. Output the proportion of successful choices by each strategy.",
  "Assign each letter of the alphabet its corresponding value ie a=1, b=2,... z=26. When given a list of words, order the words by the sum of the values of the letters in their names.\n\nE.g [shoe, hat] --> [hat, shoe]",
  "A polite number n is an integer that is the sum of two or more consecutive nonnegative integers in at least one way.\n\nYour challenge is to write a function to determine the ways if a number is polite or not.",
  "Write a function that given two sorted lists, returns a list whith the two lists merged together into one sorted list.\n\nE.g. [1,5,7,8] and [2,3,4,7,9] ---> [1,2,3,4,5,7,7,8,9].",
  "Write a function that given a number as input, will return the square root of that number, in floating point.\n\nYou are not allowed to use the library version of sqrt(), log() or exp(). In fact, only use basic arithmetic ones or bit operations",
  "Write a procedure called reverse(N, A), where N is an integer and A is an array which reverses the N first items in the array and leaves the rest intact.\n\nE.g. if N = 3 and A = [1,2,3,4,5], then reverse(N,A) --> [3,2,1,4,5].",
  "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.\n\nFind the sum of all the primes below two million.",
  "Search for a weather API and create a program that gets the 7 day forecast of any searched city.\n",
  "An emirp ('prime' spelled backwards) is a prime whose (base 10) reversal is also prime, but which is not a palindromic prime. The first few are 13, 17, 31, 37, 71, 73...\n\nImplement a function which prints out the emirps below a number(input).",
  "Write a program that takes a filename and a parameter n and prints the n most common words in the file, and the count of their occurrences, in descending order.\n",
  "Write a function that changes numbers to roman numerals. Write another one that changes it back to a number.\n\nE.g. 14 --> XIV --> 14.",
  "Write a program takes floating point number and returns the representation of American dollar coins and bills needed (rounded to the nearest penny).\n\nE.g. 12.33 --> 1 ten-dollar bill, 2 one-dollar bills, 1 quarter, 1 nickel and 3 pennies.",
  "Write a program that can do this '32-bit reverse' operation.\n\nSo 13 isn't really stored as '1101', it's stored as '00000000000000000000000000001101'.\n\nThe reverse is '10110000000000000000000000000000', which written in decimal becomes '2952790016'. ",
  "Write a program that takes a string and a parameter n and prints the n most common words in the string, and the count of their occurrences, in descending order.",
  "Your task is to implement a program that reads a string in Reverse Polish notation and prints the result of the calculation.\nYour program should support positive and negative integers and the operators +, -, *.\n",
  "Write a function that capitalizes the first letter of every word in the string and accepts a second argument a list of exceptions.\n\nThe first word of every title should ALWAYS have a capital leter.\n\nE.g. ('pizza is good', ['is']) --> 'Pizza is Good'",
  "The factorial of 10 is 3628800. The last non-zero digit of that factorial is 8.\n\nSimilarly, the last non-zero digit of the factorial of 103 is 2.\n\nCompute the last non-zero digit of the factorial of 109 .",
  "Write a program that is able to find all words in a Boggle board.\n",
  "Write a function step_count(a, b, steps) that returns a list containing steps elements, counting from a to b in steps of an equal size. Steps is always greater than 1, a and b are floating point numbers.\n\nstep_count(13.50,-20.75,3) --> [13.5,-3.625,-20.75]",
  "Write a program that reads a series of space-separated bowling rolls from input, then calculates the total score.\n\n E.g. [10, [7, 3], [7 2], [9, 1], 10, 10, 10, [2, 3], [6, 4], [7, 3, 3]] --> Total: 168",
  "The challenge today is to go from decimal notation -> scientific notation. For those that don't know, scientific notation allows for a decimal less than ten, greater than zero, and a power of ten to be multiplied.\n\nE.g. 239487 --> 2.39487 x 10^5",
  "Write out the logic for the game hangman.\n\nYou can optionally make the entire game",
  "Calculate the day of the week on any date in history.\n\nIt should take in a day, month, and year as input, and return the day of the week for that date.",
  "Write a function that calculates the intersection of two rectangles, returning either a new rectangle or some kind of null value.\n\nE.g. rectIntersection(Rect(3, 3, 10 10), Rect(6, 6, 12, 12)) --> Rect(6, 6, 10, 10)",
  "For today's challenge, you should calculate some simple statistical values without using the built in functions.\n\nGiven a data set, write functions that will calculate:\nThe mean value\nThe variance\nThe standard deviation",
  "We go through 90 minute sleep cycles during the night, and feel better waking up at the end of a sleep cycle.\n\nMake a program that takes a wake-up time and outputs the possible times to fall asleep so that you will wake up at the end of a sleep cycle.",
  "Write a program called 'censor' that takes in two arguments; a text file and list of 'bad words'.\n\nOutput the text withe the bad words censored.\n\nE.g. censor('you jerkface!', ['jerk']) --> 'you j***face!'",
  "Write a program to count the number years in an inclusive range of years that have no repeated digits.\n\nE.g. Given the range [1980, 1990], your program would return 7 (1980, 1982, 1983, 1984, 1985, 1986, 1987).",
  "Write a function that takes a string s and an integer n, and returns whether or not the string s contains at most n different characters.\n\nE.g. ncset('aacaabbabccc', 4) --> true because it contains only 3 different characters, 'a','b' and 'c', and 3 ≤ 4.",
  "Generate a Minesweeper game. Minesweeper boards have three attributes, length, width, and number of mines.\n\nMinesweeper games have two types of pieces, mines, and non-mines. The non-mines have a number, which is the number of mines adjacent to it.",
  "Write a function, where given a string, return true if it only contains the digits from 0 (zero) to 9 (nine). Else, return false.\n\nE.g. '123' --> true\n'123.123' --> false\n'abc' --> false",
  "Given a website URL, validate if the URL is well-formed, and if so, print a simple list of the key-value pairs!\n\nE.g. 'http://en.wikipedia.org/w/index.php?title=Main_Page&action=edit' --> title: 'Main_Page', action: 'edit'",
  "Write a program that decides a number between 1 and 100, and asks for your guess. If you type a number, it must either tell you if you guessed the  number or if your guess was above or below the computer's number. Then show the number of guesses taken.",
  "Write a function that prints all of the permutatons of the unique characters of a given string.\n\nE.g. permute('baz') --> baz,bza,abz,azb,zba,zab",
  "The Greatest Common Divisor of a given set of integers is the greatest integer that can divide these integers without any remainder. Write a program that takes two integers, and returns the greatest common divisor.\n\nE.g. (8,12) --> 4",
  "Write a function tipCalculator(bill, rating, amountOfPeople) to help you with your meals.\n\nE.g. tipCalculator(, 'great', 4)",
  "Write a function that checks if a word contains all the vowels in alphabetical order, non-repeated, where vowels are defined as A E I O U Y.\n\n E.g. facetiously --> true\nloquacious --> false",
  "Your goal today is to read a string of Braille characters (using standard English Braille) and print off the word in standard English letters.\n",
  "Write a program that outputs the first recurring character in a string.\n\nE.g. ABCDEBC --> B",
  "A pangram or holoalphabetic sentence for a given alphabet is a sentence using every letter of the alphabet at least once.\n\nWrite a program that takes a long sentence tells whether it is a pangram or not.",
];
