/*
  NOTE: HOW TO ADD CHALLENGES
  ---------------------------

  1. Find a programming challenge. Good places to look:
    * https://www.reddit.com/r/dailyprogrammer/wiki/challenges
    * https://www.codewars.com/
    * https://medium.com/@programmertoni/1000-hours-of-coding-challenges-in-a-year-eb8dc4f3de41
    * Make your own!

  2. Add your challenge to the BOTTOM of the array.
    * Each line is a day of the year. array[0] is Jan 1, array[31] is Feb. 1
    * If we ever have more challenges than number of days in a year, we'll make challenges2018.js, challenges2019.js, etc.

  3. Follow the requirements below:
    * The challenge has to be something that can be programmed.
    * Inlcude an example solution for clarification
    * Make sure the text is no more than 265 characters long (as I append #365daysofcode to the end).
      * Twitter won't accept it and I'll get an email saying that the string is too long.
*/

module.exports = [
  "", // Jan 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // Feb 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // Mar 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // April 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // May 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // June 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning. - Rick Cook",
  "The problem with object-oriented languages is they’ve got all this implicit environment that they carry around with them. You wanted a banana but what you got was a gorilla holding the banana and the entire jungle. - Joe Armstrong", // July 1
  "Most people find solutions to soothe their pain rather than finding and fixing the root of the problem. - someone",
  "Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime. - Waseem Latif",
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live - John Woods",
  "Things that are traditionally sync don’t have to feel sync. Things that are traditionally async don’t have to feel async. Be intentional and bridge the gap when you need. - Dan Abramov",
  "I'm not a great programmer; I'm just a good programmer with great habits. - Kent Beck",
  "Truth can only be found in one place: the code. - Robert C. Martin",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
  "A language that doesn't affect the way you think about programming is not worth knowing. - Alan J. Perlis",
  "Walking on water and developing software from a specification are easy if both are frozen. - Edward Berard",
  "This is your world. You’re the creator. Find freedom on this canvas. Believe, that you can do it, ‘Cuz you can do it. You can do it. ― Bob Ross",
  "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
  "If a baby falls 50 times while learning to walk, does it say to itself, maybe this isn't for me? - Craig S. Walker",
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. - Patrick McKenzie",
  "What one programmer can do in one month, two programmers can do in two months. - Fred Brooks",
  "Rules of Optimization:\nRule 1: Don't do it.\nRule 2 (for experts only): Don't do it yet. - Michael A. Jackson",
  "One of the best programming skills you can have is knowing when to walk away for awhile. - Oscar Godson",
  "Without requirements or design, programming is the art of adding bugs to an empty text file. - Louis Srygley",
  "It's becoming increasingly clear that we need to switch from Developers to Engineers - Jason Seegmiller",
  "People work hard for money; they will work harder for other people. But people will work hardest when they are dedicated to a cause. - Harry Emerson Fosdick",
  "Person 1: I don't want to [do something with code].\n Andrew Syriala: It’s for your own good. Like eating vegetables.",
  "Don’t accidentally deploy your js as your css.  It’ll break everything. - Sterling Chin",
  "Just because the function is stateless, doesn’t mean you can’t pass it stateful values - Jim Wharton",
  "The only difference between one that knows something and another that doesn’t is the former asked the question and learned it sooner. - Shane Barnwell",
  "Seriously, go read more code. Random repos on Github are fun. - Erik Lindblom",
  "Here’s the simple truth: you can’t innovate on products without first innovating the way you build them. - Alex Schleifer",
  "Pure functions can be read in isolation and not dependent on other lines of code. - Kyle Simpson",
  "Give a small child to draw a sun or a house and you'll almost always see the smiley face emerge - unknown",
  "Any code of your own that you haven't looked at for six or more months might as well have been written by someone else. - Eagleson's law",
  "The key to efficient development is to make interesting new mistakes. – Tom Love",
  "Testing leads to failure, and failure leads to understanding. - Burt Rutan",
  "In the end, regardless of where you are on the development hierarchy, keep coding. It’s where you’re most valuable. - The Developer's Code", // Aug 1
  "Minimize complexity. The simpler the product, the more likely you are to actually ship it, and the more likely you are to fix problems quickly. - Slava Akhmechet",
  "Documentation is a love letter that you write to your future self. - Damian Conway 💌",
  "A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
  "The object-oriented version of spaghetti code is, of course, 'lasagna code'. Too many layers. - Roberto Waltman",
  "First do it, then do it right, then do it better. - Addy Osmani",
  "Knowledge finds complexity in simplicity, while wisdom finds simplicity in complexity. - @franciscocobos",
  "Debugging is like being the detective in a crime movie where you are also the murderer. - Filipe Fortes",
  "If at first you don’t succeed, call it version 1.0. - Unknown",
  "One person's constant is another person's variable. - Susan Gerhart",
  "You pile up enough tomorrows, and you'll find you are left with nothing but a lot of empty yesterdays - Professor Harold Hill",
  "Code never lies, comments sometimes do. - Ron Jeffries",
  "Indeed, the ratio of time spent reading versus writing is well over 10 to 1. We are constantly reading old code as part of the effort to write new code. ...[Therefore,] making it easy to read makes it easier to write.",
  "One of my most productive days was throwing away 1000 lines of code. - Ken Thompson",
  "A user interface should be so simple that a beginner in an emergency can understand it within ten seconds. - Ted Nelson",
  "Theory is when you know something, but it doesn’t work. Practice is when something works, but you don’t know why. Programmers combine theory and practice: Nothing works and they don’t know why. - Unknown",
  "New programmers, take note: When people say 'simple', 'intuitive' or 'easy' they very frequently mean 'familiar to me'",
  "As a software developer, you are your own worst enemy. The sooner you realize that, the better off you’ll be. - Jeff Atwood",
  "Premature optimisation is the root of all evil (or at least most of it) in programming. - Donald Knuth",
  "We build our computer(systems) the way we build our cities: over time, without a plan, on top of ruins. - Ellen Ullman",
  "Stop driving yourself—and everyone else—crazy thinking about how to make yourself successful. Start thinking about how you’re going to make everyone around you successful. - Never Eat Alone",
  "The cheapest, fastest, and most reliable components are those that aren’t there. - Gordon Bell",
  "90% of the bugs I produced were for one of the two reasons:\n1. Doing multiple things at one place\n2. Doing one thing at multiple places - @pseudo_coder",
  "In order to understand recursion, one must first understand recursion. - Anonymous",
  "Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter. - Eric Raymond",
  "Sometimes, the elegant implementation is just a function. Not a method. Not a class. Not a framework. Just a function. - John Carmack",
  "We don't make mistakes, just happy little accidents. - Bob Ross",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
  "In carpentry, you measure twice and cut once. In software development, you never measure and make cuts until you run out of time. - Adam Morse",
  "Code is like humor. When you have to explain it, it’s bad.” – Cory House",
  "When you’re working in somebody else’s module, though, you’d better use his or her conventions. It’s part of learning to work with others. - Ray Ozzie",
  "It’s not at all important to get it right the first time. It’s vitally important to get it right the last time. - The Pragmatic Programmer", // Sept 1
  "Why do most developers fear to make continuous changes to their code? They are afraid they’ll break it! Why are they afraid they’ll break it? Because they don’t have tests. - Clean Code",
  "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it. - Brian W. Kernighan",
  "Some people, when confronted with a problem, think 'I know, I'll use regular expressions.' Now they have two problems. — Jamie Zawinski",
  "Computer Science is no more about computers than astronomy is about telescopes. — Edsger Dijkstra",
  "There are only two kinds of languages: the ones people complain about and the ones nobody uses. — Bjarne Stroustrup",
  "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // Oct 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // Nov 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // Dec 1
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "", // New Years Eve!
];
