/*
    Each Element in the array represents a week of the year
*/

module.exports = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Have you ever had that accidental horizontal scrollbar show up and don't know where in you CSS it is? Your challenge is to write a javascript function that will find all the DOM element culprits.\n\nHint 'offsetWidth' is a thing",
    "Regex is scary, but we can all get better in it. Use regex to validate the following: phone number, email address, and ABA (routing) number",
    "Parameter time! You challenge is to make a funtion that adds a parameter to the URL, another that parses the URL parameters into key value pairs, and another that removes a parameter from a URL",
    "Write a function that will save a state object to local storage every 5 seconds (throttle) if it has changed",
    "This will come in handy: write a function that inserts a comma for every three numbers as the number grows larger. \n\nexample: 20000 --> 20,000",
    "Mastermind was a board game in the 70s https://en.wikipedia.org/wiki/Mastermind_(board_game). Generate a random mastermind problem. Extra credit - write a function that checks if a mastermind answer is valid",
    "Formatting time! Better the user experience by formatting the following as the user types: SSN 111-11-1111, phone (000) 111-1111",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];
